const businessData = [
  {
    id: 10001,
    businessName: "Riverside Cafe & Bakery",
    businessOwner: "Sarah Chen",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: false,
  },
  {
    id: 10002,
    businessName: "Green Valley Landscaping",
    businessOwner: "Michael Rodriguez",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: true,
  },
  {
    id: 10003,
    businessName: "Summit Auto Repair",
    businessOwner: "James Wilson",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: false,
  },
  {
    id: 10004,
    businessName: "Coastal Fresh Market",
    businessOwner: "Lisa Patel",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: true,
  },
  {
    id: 10005,
    businessName: "Urban Edge Design Studio",
    businessOwner: "David Kim",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: false,
  },
  {
    id: 10006,
    businessName: "Maple Street Dental Care",
    businessOwner: "Emily Thompson",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: true,
  },
  {
    id: 10007,
    businessName: "Phoenix Construction Services",
    businessOwner: "Robert Martinez",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: false,
  },
  {
    id: 10008,
    businessName: "Bluebird Pet Supplies",
    businessOwner: "Jennifer Lee",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: true,
  },
  {
    id: 10009,
    businessName: "Heritage Brewing Company",
    businessOwner: "Thomas Anderson",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: false,
  },
  {
    id: 10010,
    businessName: "Evergreen Wellness Center",
    businessOwner: "Maria Garcia",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: true,
  },
  {
    id: 10011,
    businessName: "Tech Solutions Plus",
    businessOwner: "William Chang",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: false,
  },
  {
    id: 10012,
    businessName: "North Star Financial Advisors",
    businessOwner: "Rachel Cohen",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: true,
  },
  {
    id: 10013,
    businessName: "Golden Gate Photography",
    businessOwner: "Daniel Wong",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: false,
  },
  {
    id: 10014,
    businessName: "Sunset Yoga Studio",
    businessOwner: "Amanda Johnson",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: true,
  },
  {
    id: 10015,
    businessName: "Elite Home Services",
    businessOwner: "Kevin O'Brien",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: false,
  },
  {
    id: 10016,
    businessName: "Silver Lake Real Estate",
    businessOwner: "Michelle Taylor",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: true,
  },
  {
    id: 10017,
    businessName: "Artisan Woodworks",
    businessOwner: "Christopher Brown",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: false,
  },
  {
    id: 10018,
    businessName: "Modern Marketing Solutions",
    businessOwner: "Jessica Nguyen",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: true,
  },
  {
    id: 10019,
    businessName: "Harbor View Inn",
    businessOwner: "Richard Mitchell",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: false,
  },
  {
    id: 10020,
    businessName: "Cloud Nine Software",
    businessOwner: "Katherine Zhang",
    amount: Math.floor(Math.random() * 10000) + 10000,
    paymentPeriod: "Monthly",
    date: new Date().toISOString(),
    status: "PENDING",
    otherBanksHaveMadeCounterResponse: true,
  },
];

// Function to generate the full dataset
export const generateTestData = (count = 50) => {
  // If count is less than or equal to the sample data length, return a slice
  if (count <= businessData.length) {
    return businessData.slice(0, count);
  }

  // Otherwise, replicate and modify the sample data to reach desired count
  const result = [...businessData];
  const initialLength = businessData.length;

  for (let i = initialLength; i < count; i++) {
    const template = businessData[i % initialLength];
    result.push({
      ...template,
      id: 10000 + i,
      amount: Math.floor(Math.random() * 10000) + 1,
      date: new Date().toISOString(),
      otherBanksHaveMadeCounterResponse: i % 3 === 0,
    });
  }

  return result;
};

export default generateTestData;
