export enum NotificationType {
  NEW_LOAN_REQUEST = "NEW_LOAN_REQUEST",
  NEW_MESSAGE = "NEW_MESSAGE",
  BANKER_CALL = "BANKER_CALL",
  LOAN_STATUS_CHANGE = "LOAN_STATUS_CHANGE",
  COUNTER_OFFER = "COUNTER_OFFER",
}
